### ISSUE TITLE
make install-frontend fails due to checksum validation failure

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/scidash#74]
As per title, when I run the command **make install-frontend** this returns the error below.

```
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ make install-frontend
===========================
=    Install frontend     =
===========================
v7.10.1
Cloning into './static/org.geppetto.frontend'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (361/361), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 70127 (delta 218), reused 235 (delta 135), pack-reused 69766
Receiving objects: 100% (70127/70127), 26.09 MiB | 475.00 KiB/s, done.
Resolving deltas: 100% (48688/48688), done.
Checking connectivity... done.
Cloning into './static/org.geppetto.frontend/src/main/webapp/extensions/geppetto-scidash'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 2520 (delta 87), reused 105 (delta 31), pack-reused 2331
Receiving objects: 100% (2520/2520), 636.43 KiB | 702.00 KiB/s, done.
Resolving deltas: 100% (1520/1520), done.
Checking connectivity... done.
npm WARN npm npm does not support Node.js v7.10.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN tarball tarball data for file-saver@1.3.8 (sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= integrity checksum failed when using sha1: wanted sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= but got sha512-spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg== sha1-5oowx8sETi+zYrQoRp/rKRwuCdg=. (10700 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ddelpiano/.npm/_logs/2019-02-20T15_27_33_865Z-debug.log
```

An extract from the logfile

```
20327 silly extract glslify@7.0.0
20328 silly tarball trying regl-scatter2d@3.1.3 by hash: sha512-71DpYoJKAopjCP8kRgdReoBLIUre9vsoUgoWDEEeSHRsDEqIwPguhuEerxXpqY5zZ8P3COEqjYZ/sGpoeI8WCA==
20329 silly tarball trying glslify@7.0.0 by hash: sha512-yw8jDQIe9FlSH5NiZEqSAsCPj9HI7nhXgXLAgSv2Nm9eBPsFJmyN9+rNwbiozJapcj9xtc/71rMYlN9cxp1B8Q==
20330 silly extract cwise@1.0.10 extracted to /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/.staging/cwise-f278a9aa (218ms)
20331 silly extract os-locale@2.1.0 extracted to /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/.staging/os-locale-bfaf8153 (140ms)
20332 silly extract regl-line2d@3.0.13
20333 silly extract glslify@7.0.0
20334 silly tarball trying regl-line2d@3.0.13 by hash: sha512-bTsuvTw4No25kUKGiXwOm0sLJT9kZ7vAkZOZYyXLxKCMRYIz1TS0j7DfqtC5ammzni8AdSahuTT0x52RU4Izuw==
20335 silly tarball trying glslify@7.0.0 by hash: sha512-yw8jDQIe9FlSH5NiZEqSAsCPj9HI7nhXgXLAgSv2Nm9eBPsFJmyN9+rNwbiozJapcj9xtc/71rMYlN9cxp1B8Q==
20336 verbose stack Error: sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= integrity checksum failed when using sha1: wanted sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= but got sha512-spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg== sha1-5oowx8sETi+zYrQoRp/rKRwuCdg=. (10700 bytes)
20336 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
20336 verbose stack     at emitNone (events.js:91:20)
20336 verbose stack     at Transform.emit (events.js:188:7)
20336 verbose stack     at endReadableNT (_stream_readable.js:975:12)
20336 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
20336 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
20337 verbose cwd /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp
20338 verbose Linux 4.4.0-142-generic
20339 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
20340 verbose node v7.10.1
20341 verbose npm  v6.7.0
20342 error code EINTEGRITY
20343 error sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= integrity checksum failed when using sha1: wanted sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= but got sha512-spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg== sha1-5oowx8sETi+zYrQoRp/rKRwuCdg=. (10700 bytes)
20344 verbose exit [ 1, true ]
```

**Comment by ddelpiano** [comment]
bypassed/solved the issue deleting the package-lock.json in ./static/org.geppetto.frontend/src/main/webapp
