### ISSUE TITLE
make run-dev not working

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/scidash#75]
After following the installation procedure (revisited since the issue with the database creation) I tried to start the server but getting the error below.

```
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ make run-dev 
./manage.py migrate
Traceback (most recent call last):
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "scidash-postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "scidash-postgres" to address: Name or service not known

Makefile:52: recipe for target 'migrate' failed
make: *** [migrate] Error 1
``` 

Procedure followed
```
ddelpiano@GoldMarry:~/git/scidash$ git clone https://github.com/MetaCell/scidash
ddelpiano@GoldMarry:~/git/scidash$ cd scidash/
ddelpiano@GoldMarry:~/git/scidash/scidash$ cp service/dotenv/env-docker .env
ddelpiano@GoldMarry:~/git/scidash/scidash$ . .env
ddelpiano@GoldMarry:~/git/scidash/scidash$ virtualenv -p python3 ./venv
ddelpiano@GoldMarry:~/git/scidash/scidash$     source ./venv/bin/activate;
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ . .env 
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ sudo su postgres
postgres@GoldMarry:/home/ddelpiano/git/scidash/scidash/service/scripts$ ./db-create-psql.sh 
postgres@GoldMarry:/home/ddelpiano/git/scidash/scidash/service/scripts$ exit



(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ make install-backend
===========================
=    Install backend      =
===========================
Collecting asgiref==2.3.2 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/6a/ca/c141dc77da60230e393d33b5b29afbca718b7e6ce07921c42cf08af907f8/asgiref-2.3.2-py2.py3-none-any.whl
Collecting async-timeout==3.0.0 (from -r requirements.txt (line 8))
  Could not find a version that satisfies the requirement async-timeout==3.0.0 (from -r requirements.txt (line 8)) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 
1.3.0, 1.4.0, 2.0.0, 2.0.1)
No matching distribution found for async-timeout==3.0.0 (from -r requirements.txt (line 8))
Cloning into 'pygeppetto-django'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 185 (delta 20), reused 31 (delta 13), pack-reused 140
Receiving objects: 100% (185/185), 39.02 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.
Obtaining file:///home/ddelpiano/git/scidash/scidash/pygeppetto-django
Collecting channels==2.1.2 (from pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/00/3b/92d09d374dd2bc5339e4587ba4869d9bd335135f655bdecf4431c5890c5f/channels-2.1.2-py2.py3-none-any.whl
Collecting Django==1.11.7 (from pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/15/d8/b17afdcd527026d2f1acd30ac33406e6b22c0f573a3c14b2d9e0bd7df945/Django-1.11.7-py2.py3-none-any.whl
Collecting websocket-client==0.48.0 (from pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-
any.whl
Collecting requests==2.19.1 (from pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting asgiref~=2.3 (from channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/6a/ca/c141dc77da60230e393d33b5b29afbca718b7e6ce07921c42cf08af907f8/asgiref-2.3.2-py2.py3-none-any.whl
Collecting daphne~=2.2 (from channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/12/db/cecc130407d073470812f9e2f66897aa81399fa819671c8cf7b16e84366d/daphne-2.2.5-py2.py3-none-any.whl
Collecting pytz (from Django==1.11.7->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting six (from websocket-client==0.48.0->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.19.1->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.w
hl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.19.1->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests==2.19.1->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests==2.19.1->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting async-timeout<4.0,>=2.0 (from asgiref~=2.3->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/1d/b9/213521db2918b5b7f7df333a33ea3d38ba70ba705d9db6c29f0343c213ea/async_timeout-2.0.1-py3-none-any.whl
Collecting twisted>=18.7 (from daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
Collecting autobahn>=0.18 (from daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/d5/5d/49152a3ce88ad8f985a4f82ff9633a29f3ef2da050ae8aba8075142f5a61/autobahn-19.2.1-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.w
hl
Collecting constantly>=15.1 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.wh
l
Collecting Automat>=0.3.0 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/a7/b6/84d0c863ff81e8e7de87cff3bd8fd8f1054c227ce09af1b679a8b17a9274/hyperlink-18.0.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from twisted>=18.7->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/0c/dc/d715a3f2f9df4e0440e67b1dc654bcfb6dc11aac8296353eaf56164b8f01/zope.interface-4.6.0-cp35-cp35m-manyl
inux1_x86_64.whl
Collecting txaio>=18.8.1 (from autobahn>=0.18->daphne~=2.2->channels==2.1.2->pygeppetto-django==0.0.1)
  Using cached https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/ddelpiano/git/scidash/scidash/venv/lib/python3.5/site-packages (from PyHamcrest>=1.9.0->twisted>=18.7->daphn
e~=2.2->channels==2.1.2->pygeppetto-django==0.0.1) (40.8.0)
Installing collected packages: pytz, Django, async-timeout, asgiref, six, PyHamcrest, attrs, incremental, constantly, Automat, idna, hyperlink, zope.interface,
 twisted, txaio, autobahn, daphne, channels, websocket-client, certifi, chardet, urllib3, requests, pygeppetto-django
  Running setup.py develop for pygeppetto-django
Successfully installed Automat-0.7.0 Django-1.11.7 PyHamcrest-1.9.0 asgiref-2.3.2 async-timeout-2.0.1 attrs-18.2.0 autobahn-19.2.1 certifi-2018.11.29 channels-
2.1.2 chardet-3.0.4 constantly-15.1.0 daphne-2.2.5 hyperlink-18.0.0 idna-2.7 incremental-17.5.0 pygeppetto-django pytz-2018.9 requests-2.19.1 six-1.12.0 twiste
d-18.9.0 txaio-18.8.1 urllib3-1.23 websocket-client-0.48.0 zope.interface-4.6.0



(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ make install-frontend
===========================
=    Install frontend     =
===========================
v7.10.1
Cloning into './static/org.geppetto.frontend'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (361/361), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 70127 (delta 218), reused 235 (delta 135), pack-reused 69766
Receiving objects: 100% (70127/70127), 26.09 MiB | 475.00 KiB/s, done.
Resolving deltas: 100% (48688/48688), done.
Checking connectivity... done.
Cloning into './static/org.geppetto.frontend/src/main/webapp/extensions/geppetto-scidash'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 2520 (delta 87), reused 105 (delta 31), pack-reused 2331
Receiving objects: 100% (2520/2520), 636.43 KiB | 702.00 KiB/s, done.
Resolving deltas: 100% (1520/1520), done.
Checking connectivity... done.
npm WARN npm npm does not support Node.js v7.10.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN tarball tarball data for file-saver@1.3.8 (sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= integrity checksum failed when using sha1: wanted sha1-zdTETTqiZOrC9o7BZbx5HDSvEjI= but got sha512-spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg== sha1-5oowx8sETi+zYrQoRp/rKRwuCdg=. (10700 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ddelpiano/.npm/_logs/2019-02-20T15_27_33_865Z-debug.log


(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ cd static/org.geppetto.frontend/src/main/webapp/
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp$ rm package-lock.json 


(venv) ddelpiano@GoldMarry:~/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp$ npm install                                                     
npm WARN npm npm does not support Node.js v7.10.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated dat-gui@0.5.0: Use the official dat.gui: https://www.npmjs.com/package/dat.gui
npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the
 package name to 'qunit'.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated @mapbox/gl-matrix@0.0.1: This
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/uglifyjs-webpack-plug
in
> node lib/post_install.js


> gifsicle@3.0.4 postinstall /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /home/ddelpiano/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-simpletabs@0.7.0 requires a peer of react@0.12.x - 1.x but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@3.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2053 packages from 1930 contributors and audited 26409 packages in 118.577s
found 76 vulnerabilities (23 low, 43 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details


(venv) ddelpiano@GoldMarry:~/git/scidash/scidash/static/org.geppetto.frontend/src/main/webapp$ cd -
(venv) ddelpiano@GoldMarry:~/git/scidash/scidash$ cp service/geppetto/GeppettoConfiguration.json static/org.geppetto.frontend/src/main/webapp/GeppettoConfiguration.json 
```

**Comment by ddelpiano** [comment]
this has been sorted out, configuration issue.
